name: My Workflow
on:
  push:
    branches:
      - main
      - release/*
  jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Deploy
---     
- name: Install dependencies
  run: npm install

- name: Build project
  run: npm run build

- name: Deploy to UAT
  run: npm run deploy-uat
  
- name: Setup Node
  uses: actions/setup-node@v4
  with:
    node-version: '20.x'
